// Pre-populated card and benefit data for Card Keeper
// Card sortOrder (1-9) is used as a reference key for benefits

export const seedCards = [
  {
    name: "Amex Hilton Aspire #1",
    shortName: "Aspire #1",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annualFee: 550,
    currency: "USD",
    colorFrom: "#1a1a2e",
    colorTo: "#16213e",
    status: "active",
    sortOrder: 1,
  },
  {
    name: "Amex Hilton Aspire #2",
    shortName: "Aspire #2",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annualFee: 550,
    currency: "USD",
    colorFrom: "#2d1b69",
    colorTo: "#11998e",
    status: "active",
    sortOrder: 2,
  },
  {
    name: "Amex Hilton Surpass",
    shortName: "Surpass",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annualFee: 150,
    currency: "USD",
    colorFrom: "#434343",
    colorTo: "#000000",
    status: "active",
    sortOrder: 3,
  },
  {
    name: "Amex Marriott Bonvoy Brilliant",
    shortName: "Brilliant",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annualFee: 650,
    currency: "USD",
    colorFrom: "#1a1a2e",
    colorTo: "#e94560",
    status: "active",
    sortOrder: 4,
  },
  {
    name: "Chase Sapphire Preferred",
    shortName: "CSP",
    issuer: "Chase",
    network: "visa",
    country: "US",
    annualFee: 95,
    currency: "USD",
    colorFrom: "#0f2027",
    colorTo: "#2c5364",
    status: "active",
    sortOrder: 5,
  },
  {
    name: "Chase IHG One Rewards Premier",
    shortName: "IHG Premier",
    issuer: "Chase",
    network: "mastercard",
    country: "US",
    annualFee: 99,
    currency: "USD",
    colorFrom: "#1b4332",
    colorTo: "#40916c",
    status: "active",
    sortOrder: 6,
  },
  {
    name: "农行万事达尊然白金卡",
    shortName: "农行尊然白",
    issuer: "农业银行",
    network: "mastercard",
    country: "CN",
    annualFee: 880,
    currency: "CNY",
    colorFrom: "#2d3436",
    colorTo: "#636e72",
    status: "active",
    sortOrder: 7,
  },
  {
    name: "中信国航知音世界卡",
    shortName: "中信世界卡",
    issuer: "中信银行",
    network: "mastercard",
    country: "CN",
    annualFee: 0,
    currency: "CNY",
    colorFrom: "#c0392b",
    colorTo: "#8e44ad",
    status: "active",
    sortOrder: 8,
  },
  {
    name: "广发国航臻享白金卡",
    shortName: "广发臻享白",
    issuer: "广发银行",
    network: "visa",
    country: "CN",
    annualFee: 800,
    currency: "CNY",
    colorFrom: "#e74c3c",
    colorTo: "#c0392b",
    status: "active",
    sortOrder: 9,
  },
];

// Benefits template - cardSortOrder maps to the card's sortOrder above
// Actual cardId will be resolved at seed time
export type BenefitTemplate = {
  cardSortOrder: number;
  name: string;
  description: string | null;
  category: string;
  value: number | null;
  currency: string;
  cycleType: string;
  cycleReference: string;
  maxUsesPerCycle: number | null;
  maxValuePerCycle: number | null;
  activationRequired: boolean;
  activationInstructions: string | null;
  externalUrl: string | null;
  reminderDaysBefore: number;
  sortOrder: number;
};

// Helper to create Aspire benefits for card sortOrder
function aspireBenefits(sortOrder: number): BenefitTemplate[] {
  return [
    {
      cardSortOrder: sortOrder,
      name: "Hilton Diamond Status",
      description: "自动获得希尔顿最高等级钻石会籍，含房型升级、行政酒廊、早餐等",
      category: "status",
      value: null,
      currency: "USD",
      cycleType: "ongoing",
      cycleReference: "calendar",
      maxUsesPerCycle: null,
      maxValuePerCycle: null,
      activationRequired: false,
      activationInstructions: null,
      externalUrl: null,
      reminderDaysBefore: 0,
      sortOrder: 1,
    },
    {
      cardSortOrder: sortOrder,
      name: "Hilton Resort Credit",
      description: "在希尔顿度假村酒店消费可获 statement credit，每半年 $200",
      category: "credit",
      value: 200,
      currency: "USD",
      cycleType: "semi_annual",
      cycleReference: "calendar",
      maxUsesPerCycle: null,
      maxValuePerCycle: 200,
      activationRequired: false,
      activationInstructions: null,
      externalUrl: "https://www.hilton.com/en/hilton-honors/credit-cards/",
      reminderDaysBefore: 30,
      sortOrder: 2,
    },
    {
      cardSortOrder: sortOrder,
      name: "Airline Credit",
      description: "直接购买机票或通过 AmexTravel 可获 statement credit，每季度 $50",
      category: "credit",
      value: 50,
      currency: "USD",
      cycleType: "quarterly",
      cycleReference: "calendar",
      maxUsesPerCycle: null,
      maxValuePerCycle: 50,
      activationRequired: false,
      activationInstructions: null,
      externalUrl: null,
      reminderDaysBefore: 14,
      sortOrder: 3,
    },
    {
      cardSortOrder: sortOrder,
      name: "CLEAR+ Credit",
      description: "CLEAR+ 会员年费全额报销",
      category: "credit",
      value: 209,
      currency: "USD",
      cycleType: "annual",
      cycleReference: "calendar",
      maxUsesPerCycle: null,
      maxValuePerCycle: 209,
      activationRequired: true,
      activationInstructions: "需注册并用 Aspire 卡支付 CLEAR+ 自动续费会员",
      externalUrl: "https://www.clearme.com/",
      reminderDaysBefore: 30,
      sortOrder: 4,
    },
    {
      cardSortOrder: sortOrder,
      name: "Waldorf/Conrad Property Credit",
      description: "通过专属链接预订华尔道夫或康莱德酒店（2晚起），每次住宿享 $100 酒店消费额度",
      category: "credit",
      value: 100,
      currency: "USD",
      cycleType: "per_event",
      cycleReference: "calendar",
      maxUsesPerCycle: null,
      maxValuePerCycle: null,
      activationRequired: true,
      activationInstructions: "必须通过 HiltonHonorsAspireCard.com 或电话 (855) 292-5757 预订",
      externalUrl: "https://www.hiltonhonorsaspirecard.com/",
      reminderDaysBefore: 0,
      sortOrder: 5,
    },
    {
      cardSortOrder: sortOrder,
      name: "Free Night Certificate",
      description: "开卡周年赠送免费住宿一晚，无积分上限，可用于任何希尔顿酒店",
      category: "free_night",
      value: 500,
      currency: "USD",
      cycleType: "annual",
      cycleReference: "anniversary",
      maxUsesPerCycle: 1,
      maxValuePerCycle: null,
      activationRequired: false,
      activationInstructions: null,
      externalUrl: null,
      reminderDaysBefore: 60,
      sortOrder: 6,
    },
    {
      cardSortOrder: sortOrder,
      name: "Free Night at $30K Spend",
      description: "年度消费满 $30,000 额外获得一晚免费住宿",
      category: "free_night",
      value: 500,
      currency: "USD",
      cycleType: "annual",
      cycleReference: "calendar",
      maxUsesPerCycle: 1,
      maxValuePerCycle: null,
      activationRequired: false,
      activationInstructions: null,
      externalUrl: null,
      reminderDaysBefore: 30,
      sortOrder: 7,
    },
    {
      cardSortOrder: sortOrder,
      name: "Free Night at $60K Spend",
      description: "年度消费满 $60,000 再获得一晚免费住宿",
      category: "free_night",
      value: 500,
      currency: "USD",
      cycleType: "annual",
      cycleReference: "calendar",
      maxUsesPerCycle: 1,
      maxValuePerCycle: null,
      activationRequired: false,
      activationInstructions: null,
      externalUrl: null,
      reminderDaysBefore: 30,
      sortOrder: 8,
    },
  ];
}

export const seedBenefitsTemplate: BenefitTemplate[] = [
  // ─── Aspire #1 (sortOrder 1) ──────────────────────────────────────
  ...aspireBenefits(1),

  // ─── Aspire #2 (sortOrder 2) ──────────────────────────────────────
  ...aspireBenefits(2),

  // ─── Surpass (sortOrder 3) ────────────────────────────────────────
  {
    cardSortOrder: 3,
    name: "Hilton Gold Status",
    description: "自动获得希尔顿金卡会籍，含房型升级和早餐（部分品牌）；年消费 $40K 可升钻石",
    category: "status",
    value: null,
    currency: "USD",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 1,
  },
  {
    cardSortOrder: 3,
    name: "Hilton Property Credit",
    description: "在任何希尔顿酒店消费可获 statement credit，每季度 $50",
    category: "credit",
    value: 50,
    currency: "USD",
    cycleType: "quarterly",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: 50,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 14,
    sortOrder: 2,
  },
  {
    cardSortOrder: 3,
    name: "Free Night at $15K Spend",
    description: "年度消费满 $15,000 获得一晚免费住宿（无积分上限）",
    category: "free_night",
    value: 400,
    currency: "USD",
    cycleType: "annual",
    cycleReference: "calendar",
    maxUsesPerCycle: 1,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 60,
    sortOrder: 3,
  },

  // ─── Brilliant (sortOrder 4) ──────────────────────────────────────
  {
    cardSortOrder: 4,
    name: "Marriott Platinum Elite + 25 Elite Nights",
    description: "自动获得万豪白金会籍 + 每年 25 晚精英房晚，含套房升级、酒廊、早餐",
    category: "status",
    value: null,
    currency: "USD",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 1,
  },
  {
    cardSortOrder: 4,
    name: "Monthly Dining Credit",
    description: "全球餐厅消费可获 statement credit，每月 $25（不限万豪餐厅）",
    category: "credit",
    value: 25,
    currency: "USD",
    cycleType: "monthly",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: 25,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 7,
    sortOrder: 2,
  },
  {
    cardSortOrder: 4,
    name: "Ritz/St.Regis Property Credit",
    description: "预订丽思卡尔顿或瑞吉酒店（2晚起），每次住宿享 $100 酒店消费额度",
    category: "credit",
    value: 100,
    currency: "USD",
    cycleType: "per_event",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: true,
    activationInstructions: "需在 marriottbonvoy.com 登录后选择 Luxury Credit Card Rate 预订",
    externalUrl: "https://www.marriott.com/",
    reminderDaysBefore: 0,
    sortOrder: 3,
  },
  {
    cardSortOrder: 4,
    name: "Priority Pass Select",
    description: "持卡人+2位同行免费使用全球 1,700+ 机场贵宾厅",
    category: "lounge",
    value: null,
    currency: "USD",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: true,
    activationInstructions: "需在 Amex 官网注册 Priority Pass 会员并获取卡片",
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 4,
  },
  {
    cardSortOrder: 4,
    name: "Free Night Certificate",
    description: "开卡周年赠送免费住宿一晚，最高可用于 85,000 点/晚酒店（可加 25K 点到 110K）",
    category: "free_night",
    value: 595,
    currency: "USD",
    cycleType: "annual",
    cycleReference: "anniversary",
    maxUsesPerCycle: 1,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 60,
    sortOrder: 5,
  },
  {
    cardSortOrder: 4,
    name: "Global Entry / TSA PreCheck Credit",
    description: "Global Entry 申请费全额报销（$120），每 4 年一次",
    category: "travel",
    value: 120,
    currency: "USD",
    cycleType: "one_time",
    cycleReference: "calendar",
    maxUsesPerCycle: 1,
    maxValuePerCycle: 120,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 6,
  },
  {
    cardSortOrder: 4,
    name: "Trip Delay Insurance",
    description: "航班延误 6 小时以上，每次行程最高赔付 $500（餐饮、住宿等合理费用）",
    category: "insurance",
    value: 500,
    currency: "USD",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 7,
  },

  // ─── CSP (sortOrder 5) ────────────────────────────────────────────
  {
    cardSortOrder: 5,
    name: "Hotel Credit via Chase Travel",
    description: "通过 Chase Travel 预订酒店可获 $50 statement credit（开卡周年重置）",
    category: "credit",
    value: 50,
    currency: "USD",
    cycleType: "annual",
    cycleReference: "anniversary",
    maxUsesPerCycle: null,
    maxValuePerCycle: 50,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 30,
    sortOrder: 1,
  },
  {
    cardSortOrder: 5,
    name: "DoorDash DashPass + $10/月",
    description: "免费 DashPass 会员（省配送费）+ 每月 $10 非餐厅订单 credit（截至 2027.12）",
    category: "credit",
    value: 10,
    currency: "USD",
    cycleType: "monthly",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: 10,
    activationRequired: true,
    activationInstructions: "需在 DoorDash 中激活 DashPass 并绑定 CSP 卡",
    externalUrl: "https://www.doordash.com/dashpass/",
    reminderDaysBefore: 7,
    sortOrder: 2,
  },
  {
    cardSortOrder: 5,
    name: "10% Anniversary Points Bonus",
    description: "开卡周年自动获得上一年总消费额 10% 的额外 UR 积分",
    category: "points",
    value: null,
    currency: "USD",
    cycleType: "annual",
    cycleReference: "anniversary",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 3,
  },
  {
    cardSortOrder: 5,
    name: "Primary Rental Car Insurance",
    description: "美国租车 Primary CDW 保险（无需走个人车险），覆盖最高 $60,000",
    category: "insurance",
    value: null,
    currency: "USD",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 4,
  },
  {
    cardSortOrder: 5,
    name: "Trip Delay Insurance",
    description: "航班延误 12 小时以上，每张票最高赔付 $500",
    category: "insurance",
    value: 500,
    currency: "USD",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 5,
  },
  {
    cardSortOrder: 5,
    name: "Trip Cancellation Insurance",
    description: "行程取消/中断保险，每人最高 $10,000，每次行程最高 $20,000",
    category: "insurance",
    value: null,
    currency: "USD",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 6,
  },

  // ─── IHG Premier (sortOrder 6) ────────────────────────────────────
  {
    cardSortOrder: 6,
    name: "IHG Platinum Elite Status",
    description: "自动获得 IHG 白金精英会籍（房型升级、欢迎礼、延迟退房等）；年消费 $40K 升钻石",
    category: "status",
    value: null,
    currency: "USD",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 1,
  },
  {
    cardSortOrder: 6,
    name: "Free Night Certificate",
    description: "开卡周年赠送免费住宿一晚（40,000 点上限，可用自己的积分补差价）",
    category: "free_night",
    value: 200,
    currency: "USD",
    cycleType: "annual",
    cycleReference: "anniversary",
    maxUsesPerCycle: 1,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 60,
    sortOrder: 2,
  },
  {
    cardSortOrder: 6,
    name: "United TravelBank Credit",
    description: "每半年自动存入 $25 到 United TravelBank 账户（1月和7月），可用于买美联航机票",
    category: "credit",
    value: 25,
    currency: "USD",
    cycleType: "semi_annual",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: 25,
    activationRequired: true,
    activationInstructions: "需将 IHG Premier 卡与 United MileagePlus 账户关联",
    externalUrl: null,
    reminderDaysBefore: 14,
    sortOrder: 3,
  },
  {
    cardSortOrder: 6,
    name: "4th Night Free on Awards",
    description: "用 IHG 积分预订连住 4 晚+，第 4 晚免费（省 25%）",
    category: "travel",
    value: null,
    currency: "USD",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 4,
  },
  {
    cardSortOrder: 6,
    name: "Global Entry / TSA PreCheck Credit",
    description: "Global Entry 申请费全额报销（$120），每 4 年一次",
    category: "travel",
    value: 120,
    currency: "USD",
    cycleType: "one_time",
    cycleReference: "calendar",
    maxUsesPerCycle: 1,
    maxValuePerCycle: 120,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 5,
  },
  {
    cardSortOrder: 6,
    name: "Cell Phone Protection",
    description: "用此卡交手机费，手机被盗或损坏可赔 $800/次（$50 免赔额，年上限 $1,000）",
    category: "insurance",
    value: 800,
    currency: "USD",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: true,
    activationInstructions: "必须用 IHG Premier 卡支付每月手机话费账单",
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 6,
  },

  // ─── 农行尊然白 (sortOrder 7) ─────────────────────────────────────
  {
    cardSortOrder: 7,
    name: "机场贵宾厅",
    description: "2026年起每年 6 次免费农行自营贵宾厅，用完后可用 6 万积分换 1 次（最多加购 3 次）",
    category: "lounge",
    value: null,
    currency: "CNY",
    cycleType: "annual",
    cycleReference: "calendar",
    maxUsesPerCycle: 6,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 30,
    sortOrder: 1,
  },
  {
    cardSortOrder: 7,
    name: "接送机服务",
    description: "10 万积分兑换 1 次境内接送机，全年上限 12 次",
    category: "travel",
    value: null,
    currency: "CNY",
    cycleType: "annual",
    cycleReference: "calendar",
    maxUsesPerCycle: 12,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 2,
  },
  {
    cardSortOrder: 7,
    name: "航空延误险",
    description: "到达延误 2 小时以上，最高赔 300 元/次，每月最多 2 次，年度 6 次",
    category: "insurance",
    value: 300,
    currency: "CNY",
    cycleType: "monthly",
    cycleReference: "calendar",
    maxUsesPerCycle: 2,
    maxValuePerCycle: null,
    activationRequired: true,
    activationInstructions: "每次出行前须在农行 APP → 信用卡 → 高端专区领取延误险券（首笔刷卡 4 日后可领）",
    externalUrl: null,
    reminderDaysBefore: 3,
    sortOrder: 3,
  },
  {
    cardSortOrder: 7,
    name: "专家预约挂号",
    description: "全年 3 次预约挂号 + 全程陪同就诊（取号、划价、取药）",
    category: "lifestyle",
    value: null,
    currency: "CNY",
    cycleType: "annual",
    cycleReference: "calendar",
    maxUsesPerCycle: 3,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 60,
    sortOrder: 4,
  },
  {
    cardSortOrder: 7,
    name: "年度体检",
    description: "全年 1 次尊贵体检套餐（爱康国宾/美年大健康/瑞慈等）",
    category: "lifestyle",
    value: null,
    currency: "CNY",
    cycleType: "annual",
    cycleReference: "calendar",
    maxUsesPerCycle: 1,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 90,
    sortOrder: 5,
  },
  {
    cardSortOrder: 7,
    name: "道路救援",
    description: "全年 24 小时不限次免费道路救援（拖车、换胎、搭电等），覆盖全国",
    category: "travel",
    value: null,
    currency: "CNY",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 6,
  },
  {
    cardSortOrder: 7,
    name: "万事达消费达标礼",
    description: "每季度消费达标可获高端酒店/国航升舱券等礼遇（关注农行公告）",
    category: "lifestyle",
    value: null,
    currency: "CNY",
    cycleType: "quarterly",
    cycleReference: "calendar",
    maxUsesPerCycle: 1,
    maxValuePerCycle: null,
    activationRequired: true,
    activationInstructions: "需关注农行 APP 公告并报名参加活动",
    externalUrl: null,
    reminderDaysBefore: 14,
    sortOrder: 7,
  },

  // ─── 中信世界卡 (sortOrder 8) ─────────────────────────────────────
  {
    cardSortOrder: 8,
    name: "国航凤凰知音金卡",
    description: "自动享有国航两舱休息室、优先登机、额外行李额等金卡权益",
    category: "status",
    value: null,
    currency: "CNY",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 1,
  },
  {
    cardSortOrder: 8,
    name: "龙腾贵宾厅",
    description: "每年 8 个龙腾点数（机场 1 点/次，高铁 0.5 点/次）",
    category: "lounge",
    value: null,
    currency: "CNY",
    cycleType: "annual",
    cycleReference: "calendar",
    maxUsesPerCycle: 8,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 30,
    sortOrder: 2,
  },
  {
    cardSortOrder: 8,
    name: "36+1 生活权益点",
    description: "每月消费达标获权益点（2000元=2点, 4000元=4点, 6000元=6点），可兑换健身、SPA、洁牙等",
    category: "lifestyle",
    value: null,
    currency: "CNY",
    cycleType: "monthly",
    cycleReference: "calendar",
    maxUsesPerCycle: 6,
    maxValuePerCycle: null,
    activationRequired: true,
    activationInstructions: "需每月消费达标，权益点有效期至当年 12 月 31 日",
    externalUrl: null,
    reminderDaysBefore: 7,
    sortOrder: 3,
  },
  {
    cardSortOrder: 8,
    name: "预约挂号",
    description: "每年费年度内 5 个权益点（主卡），持卡人本人及 1 名家人共享",
    category: "lifestyle",
    value: null,
    currency: "CNY",
    cycleType: "annual",
    cycleReference: "calendar",
    maxUsesPerCycle: 5,
    maxValuePerCycle: null,
    activationRequired: true,
    activationInstructions: "至少提前 3 个工作日致电 40060-95558 预约",
    externalUrl: null,
    reminderDaysBefore: 60,
    sortOrder: 4,
  },
  {
    cardSortOrder: 8,
    name: "首都机场免费停车",
    description: "T2/T3 停车楼中信专用停车区，48 小时免费，全年 36 次",
    category: "travel",
    value: null,
    currency: "CNY",
    cycleType: "annual",
    cycleReference: "calendar",
    maxUsesPerCycle: 36,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 5,
  },
  {
    cardSortOrder: 8,
    name: "航班延误险",
    description: "用本卡购买机票，延误 2 小时赔 1000 元，延误 4 小时赔 2000 元",
    category: "insurance",
    value: 1000,
    currency: "CNY",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 6,
  },
  {
    cardSortOrder: 8,
    name: "里程累积",
    description: "8 元=1 凤凰知音里程（线上月上限 2000 里程），微信/支付宝消费最稳定",
    category: "points",
    value: null,
    currency: "CNY",
    cycleType: "monthly",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 7,
  },

  // ─── 广发臻享白 (sortOrder 9) ─────────────────────────────────────
  {
    cardSortOrder: 9,
    name: "广发自营+龙腾贵宾厅（不限次）",
    description: "广发自营机场贵宾厅、龙腾机场贵宾厅均不限次使用，不可带人",
    category: "lounge",
    value: null,
    currency: "CNY",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 1,
  },
  {
    cardSortOrder: 9,
    name: "高铁贵宾厅（不限次）",
    description: "广发自营高铁贵宾厅不限次使用",
    category: "lounge",
    value: null,
    currency: "CNY",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 2,
  },
  {
    cardSortOrder: 9,
    name: "预约挂号",
    description: "三甲医院预约挂号，全年 3 次",
    category: "lifestyle",
    value: null,
    currency: "CNY",
    cycleType: "annual",
    cycleReference: "calendar",
    maxUsesPerCycle: 3,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 60,
    sortOrder: 3,
  },
  {
    cardSortOrder: 9,
    name: "导医导诊",
    description: "全年 3 次导医导诊服务",
    category: "lifestyle",
    value: null,
    currency: "CNY",
    cycleType: "annual",
    cycleReference: "calendar",
    maxUsesPerCycle: 3,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 60,
    sortOrder: 4,
  },
  {
    cardSortOrder: 9,
    name: "生日月双倍里程",
    description: "生日当月刷卡消费享 2 倍里程累积",
    category: "points",
    value: null,
    currency: "CNY",
    cycleType: "annual",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 30,
    sortOrder: 5,
  },
  {
    cardSortOrder: 9,
    name: "餐食厅权益",
    description: "广发合作餐食厅权益，使用间隔 5 小时",
    category: "lifestyle",
    value: null,
    currency: "CNY",
    cycleType: "monthly",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: true,
    activationInstructions: "上月名下任意广发卡消费满 3000 元方可使用本月餐食厅权益",
    externalUrl: null,
    reminderDaysBefore: 5,
    sortOrder: 6,
  },
  {
    cardSortOrder: 9,
    name: "道路救援",
    description: "道路救援 + 酒后代驾服务",
    category: "travel",
    value: null,
    currency: "CNY",
    cycleType: "ongoing",
    cycleReference: "calendar",
    maxUsesPerCycle: null,
    maxValuePerCycle: null,
    activationRequired: false,
    activationInstructions: null,
    externalUrl: null,
    reminderDaysBefore: 0,
    sortOrder: 7,
  },
];
